global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    cluster: "local-docker"

remote_write:
  - url: "http://mimir:9009/api/v1/push"
    headers:
      X-Scope-OrgID: 'SnkrShop'
    queue_config:
      capacity: 5000
      max_shards: 10
      max_samples_per_send: 2000
      batch_send_deadline: 5s
    metadata_config:
      send: true

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 30s
    scrape_timeout: 30s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: "grafana"
    scrape_interval: 30s
    scrape_timeout: 30s
    scheme: http
    metrics_path: /metrics
    static_configs: 
      - targets: ["host.docker.internal:3000"]

  - job_name: "loki"
    scrape_interval: 30s
    scrape_timeout: 30s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:3100"]

  - job_name: "tempo"
    scrape_interval: 30s
    scrape_timeout: 30s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:3200"]
        labels:
          job: tempo
          instance: tempo-1

  - job_name: "mimir"
    scrape_interval: 30s
    scrape_timeout: 30s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9009"]

  - job_name: 'postgres'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets: ['host.docker.internal:9187']

  - job_name: 'snkrshop-api'
    scrape_interval: 30s
    scrape_timeout: 30s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ['snkrshop.homelab.local']
