global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    cluster: "local-docker"

remote_write:
  - url: "http://mimir:9009/api/v1/push"
    headers:
      X-Scope-OrgID: 'SnkrShop'
    queue_config:
      capacity: 5000
      max_shards: 10
      max_samples_per_send: 2000
      batch_send_deadline: 5s
    metadata_config:
      send: true

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["grafana.homelab.local:9090"]

  - job_name: "grafana"
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["grafana.homelab.local:3000"]

  - job_name: "loki"
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["grafana.homelab.local:3100"]

  - job_name: 'fastapi-backend'
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ['snkrshop.homelab.local']

  - job_name: "tempo"
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["grafana.homelab.local:3200"]
        labels:
          job: tempo
          instance: tempo-1

  - job_name: "mimir"
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["grafana.homelab.local:9009"]
